### ISSUE TITLE
seems like the code for crawing the rank info is missing?

### ISSUE THREAD

**Issue by LividWo** [n1k0ver3E/NFT_Monitor#1]

**Comment by n1k0ver3E** [comment]
The ranking is not included in the metadata, so this is no crawling process. 
It simply calculates a rarity score for each trait by using the formula, 

`Score = 1/((Number of NFTs with that trait)/1000)`

Then ranked by the score in descending order.

More detail can be found on https://raritytools.medium.com/ranking-rarity-understanding-rarity-calculation-methods-86ceaeb9b98c
